version: '{build}'
os: Visual Studio 2015

cache:
- vcpkg -> .appveyor.yml

platform:
  - x64

configuration:
  - Debug

environment:
  matrix:
  - SHARED: OFF
  - SHARED: ON
  
matrix:
  fast_finish: true

init: []

before_build:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015" -D CMAKE_GENERATOR_PLATFORM=%platform% -D BUILD_SHARED_LIBS=%SHARED% -D SAMPLES=ON -D BENCHMARKS=ON ..

build:
  project: build/xlnt_all.sln
  parallel: true
  verbosity: minimal

test_script:
  - tests\%configuration%\xlnt.test.exe
  - samples\%configuration%\sample-documentation.exe
